modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://psychologystory.xyz/"
[[mods]]
modId="colorbrickmod"
version="${file.jarVersion}"
displayName="Color Brick Mod"
updateJSONURL="http://psychologystory.xyz/"
displayURL="http://psychologystory.xyz/"
logoFile="cbmod.png"
credits="Color Brick Modification Project Team"
authors="JunTae Son"
description='''
Minecraft Color Brick Modification
Made by JunTae Son
'''
[[dependencies.hapysusmod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hapysusmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
